### ISSUE TITLE
Speaker submitted URLs are being changed

### ISSUE THREAD

**Issue by MelSumner** [tildeio/cfp-app#14]
The URLs submitted by the speakers (video and head shot) are getting all lowercased, which will make them not work if they come from websites where this matters. I noticed that the first letter is getting capitalized, which points to `text-transform: capitalize;` or similar. 

Perhaps it's being changed here?
![image](https://user-images.githubusercontent.com/4587451/33093505-bfc5aadc-cec2-11e7-9b91-100273b761ea.png)

**Comment by wifelette** [comment]
Peter fixed this last week :)
